DROP TABLE IF EXISTS detalles_pedido;
DROP TABLE IF EXISTS pedidos;
DROP TABLE IF EXISTS solicitudes_servicio;
DROP TABLE IF EXISTS servicios;
DROP TABLE IF EXISTS productos;
DROP TABLE IF EXISTS categorias;
DROP TABLE IF EXISTS clientes;
DROP TABLE IF EXISTS usuarios_roles;
DROP TABLE IF EXISTS usuarios;
DROP TABLE IF EXISTS roles;

CREATE TABLE roles (id BIGINT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(40) NOT NULL UNIQUE);
CREATE TABLE usuarios (id BIGINT AUTO_INCREMENT PRIMARY KEY, correo VARCHAR(120) NOT NULL UNIQUE, clave VARCHAR(255) NOT NULL, activo BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE usuarios_roles (usuario_id BIGINT NOT NULL, rol_id BIGINT NOT NULL, PRIMARY KEY(usuario_id, rol_id), FOREIGN KEY(usuario_id) REFERENCES usuarios(id), FOREIGN KEY(rol_id) REFERENCES roles(id));
CREATE TABLE clientes (id BIGINT AUTO_INCREMENT PRIMARY KEY, usuario_id BIGINT UNIQUE, nombre VARCHAR(120) NOT NULL, telefono VARCHAR(30), direccion VARCHAR(300), FOREIGN KEY(usuario_id) REFERENCES usuarios(id));
CREATE TABLE categorias (id BIGINT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(80) NOT NULL UNIQUE, descripcion VARCHAR(240), activo BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE productos (id BIGINT AUTO_INCREMENT PRIMARY KEY, categoria_id BIGINT NOT NULL, sku VARCHAR(40) NOT NULL UNIQUE, nombre VARCHAR(120) NOT NULL, descripcion VARCHAR(500), precio DECIMAL(12,2) NOT NULL, existencia INT NOT NULL DEFAULT 0, destacado BOOLEAN NOT NULL DEFAULT FALSE, activo BOOLEAN NOT NULL DEFAULT TRUE, FOREIGN KEY(categoria_id) REFERENCES categorias(id));
CREATE TABLE servicios (id BIGINT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(120) NOT NULL, descripcion VARCHAR(500), precio_base DECIMAL(12,2), activo BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE solicitudes_servicio (id BIGINT AUTO_INCREMENT PRIMARY KEY, cliente_id BIGINT NOT NULL, servicio_id BIGINT NOT NULL, fecha_solicitud TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, fecha_visita TIMESTAMP, estado VARCHAR(30) NOT NULL, observaciones VARCHAR(800), FOREIGN KEY(cliente_id) REFERENCES clientes(id), FOREIGN KEY(servicio_id) REFERENCES servicios(id));
CREATE TABLE pedidos (id BIGINT AUTO_INCREMENT PRIMARY KEY, cliente_id BIGINT NOT NULL, fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, estado VARCHAR(30) NOT NULL, subtotal DECIMAL(12,2) NOT NULL, impuesto DECIMAL(12,2) NOT NULL, total DECIMAL(12,2) NOT NULL, FOREIGN KEY(cliente_id) REFERENCES clientes(id));
CREATE TABLE detalles_pedido (id BIGINT AUTO_INCREMENT PRIMARY KEY, pedido_id BIGINT NOT NULL, producto_id BIGINT NOT NULL, cantidad INT NOT NULL, precio_unitario DECIMAL(12,2) NOT NULL, subtotal DECIMAL(12,2) NOT NULL, FOREIGN KEY(pedido_id) REFERENCES pedidos(id), FOREIGN KEY(producto_id) REFERENCES productos(id));

CREATE INDEX idx_producto_categoria ON productos(categoria_id);
CREATE INDEX idx_pedido_cliente ON pedidos(cliente_id);
CREATE INDEX idx_solicitud_estado ON solicitudes_servicio(estado);
